{% set name = "instructor" %}
{% set version = "1.10.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jxnl/instructor/archive/refs/tags/{{ version }}.tar.gz
  sha256: 23ae40151fcd2d905702c4ca609780cb8c587b2910b61c435fcc7644b27bb977

build:
  entry_points:
    - instructor = instructor.cli.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - openai >=1.82.0,<2.0.0
    - pydantic >=2.10.4,<3.0.0
    - docstring_parser >=0.16.0,<0.17.0
    - typer >=0.12.3,<1.0.0
    - rich >=13.7.1,<15.0.0
    - aiohttp >=3.11.11,<4.0.0
    - requests >=2.32.3
    - tenacity ==8.2.3
    - pydantic-core >=2.27.2,<3.0.0
    - jiter >=0.6.1,<0.7
    - jinja2 >=3.1.4
    - diskcache >=5.6.3,<6.0.0
  run_constrained:
    - fastapi ==0.115.6,<0.116.0
    - redis-py ==5.0.4,<6.0.0
    - pandas >=2.2.2,<3.0.0
    - tabulate >=0.9.0,<0.10.0
    - pydantic_extra_types >=2.7.0,<3.0.0
    - litellm >=1.37.19,<2.0.0
    - anthropic >=0.53.0,<0.54.0
    - xmltodict >=0.13.0,<0.15.0
    - groq >=0.5.0,<0.6.0
    - cohere >=5.3.4,<6.0.0
    - mistralai >=0.2.0,<0.3.0

test:
  imports:
    - instructor
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jxnl/instructor
  summary: structured outputs for llm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
