{% set name = "instructor" %}
{% set version = "1.9.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jxnl/instructor/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9d0b058418ee9ab75b8e5f841df52007d303d7f3364627499f0b37a05cc4f07d

build:
  entry_points:
    - instructor = instructor.cli.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - openai >=1.52.0,<2.0.0
    - pydantic >=2.8.0,<3.0.0
    - docstring_parser >=0.16.0,<0.17.0
    - typer >=0.9.0,<1.0.0
    - rich >=13.7.0,<14.0.0
    - aiohttp >=3.9.1,<4.0.0
    - requests >=2.32.3
    - tenacity >=9.0.0,<10.0.0
    - pydantic-core >=2.18.0,<3.0.0
    - jiter >=0.6.1,<0.7
    - jinja2 >=3.1.4
  run_constrained:
    - fastapi >=0.109.2,<0.110.0
    - redis-py >=5.0.1,<6.0.0
    - diskcache >=5.6.3,<6.0.0
    - pandas >=2.2.0,<3.0.0
    - tabulate >=0.9.0,<0.10.0
    - pydantic_extra_types >=2.6.0,<3.0.0
    - litellm >=1.0.0,<2.0.0
    - anthropic >=0.23.1,<0.24.0
    - xmltodict >=0.13.0,<0.14.0
    - groq >=0.4.2,<0.5.0
    - cohere >=5.1.8,<6.0.0
    - mistralai >=0.1.8,<0.2.0

test:
  imports:
    - instructor
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jxnl/instructor
  summary: structured outputs for llm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
